### ISSUE TITLE
Do you have some related paper about this work?

### ISSUE THREAD

**Issue by filipegomes** [jimmycallin/pydsm#2]
Hello!

First of all, that is a very nice work. Thanks for share with us!

Did you publish some paper or another scientific work on this implementation? I am currently work on a project and the pydsm is being a really great help. But my master's advisor asked about related papers.

**Comment by jimmycallin** [comment]
@filipegomes so sorry about the late reply, for some reason I never got a notification about your issue.

I never published a paper on this, as it was more of a hobby thing I did aside from my master's. I'm so happy to hear that it has been of help in your project. Best of luck!
